baseurl = ""
title = "ASM News"
theme = "hugo-tracks-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Use custom.css for your custom styling
  style = "default"
  description = "Describe your website"
  copyright = "&copy;2016 Your name or company"
  sidebarAbout = [
    "I am a creative illustrator and graphic designer with more than 10 years of experience.",
    "Originally from Toronto, currently based in London."
  ]

  [[params.navlinks]]
  name = "Home"
  url = ""

  [params.social]
  facebook      = "full page or profile url in facebook"
  googleplus    = "full profile url in googleplus"
  email         = "email@example.com"
  twitter       = "full profile url in twitter"
  instagram     = "full profile url in instagram"
